### ISSUE TITLE
Mixed performances with the same name quartet

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore#174]
There is a new quartet in SUN Easy Street form my chapter. They name was used before 4-5 times with different names. How to remove the performances from this NEWBIE #504093, as they are just getting ready for their first official contest?

**Comment by russkibass** [comment]
I don't think we need to list previous performances of quartet members in quartets OTHER THAN the named entry. I know these guys and neither one of them sang as Easy Street. Paul Carter and Bryn Havel sang in the same quartet that competed in SUN, so did Charlie Nelson and maybe David Cross. Why not list this under Performers?

**Comment by dbinetti** [comment]
i'm sorry, but i'm not fully understanding.  

the system thinks of entities in terms of BHS ID (the primary key).  so is this a new group, with a new ID, or the same group, with the old ID but a new name?

**Comment by dbinetti** [comment]
Reopen - closed by accident

**Comment by russkibass** [comment]
There are several quartets - current and past performers with the name Easy Street. BHS now lists just one 
![screen shot 2016-04-23 at 2 36 30](https://cloud.githubusercontent.com/assets/8118886/14763345/d8649680-0960-11e6-8f8d-a8b85580663a.png)
Last time I checked barberscore there were 4 with the name Easy Street. None of them listed any performance, except ES with Dave Cross as lead. I was not sure whether these performances were of the previous Easy Streets or of the previous quartets where current members of Easy Street sang. Either way I find listing performances where current members sang is confusing in the Groups tab. Better place in the Persons tab, IMHO

**Comment by dbinetti** [comment]
i agree.  we'll change this.
