### ISSUE TITLE
Adding new roles/persons

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore#188]
Tried adding new roles for Ohana Means Family quartet that listed only tenor. went to api/persons trying to add new role to existing person but was not able to add the lead to Ryan Modrall who is already listed as person. The system pushed me away rather than back to new roles

**Comment by dbinetti** [comment]
I looked and this appears correct.  Were you able to fix on your own or was it something else?  Closing

**Comment by russkibass** [comment]
You added that tab n I was able to add new roles 

-- 
Alexander Boltenko 
"Russki" Bass, St. Petersburg, FL
russkibass@barbershopharmony.org
@RusskibassTampa
singing bass with the Heralds of Harmony
Cell 269-501-SING (7464)
http://barberscore.com - best International contests tracker & database
"Barbershop quartet singing is four guys tasting the holy essence of four individual mechanisms coming into complete agreement."  (Meredith Willson)
